auth:
  registry.cn-guangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/sig-storage/csi-attacher: antidebug/docker-image-sync/csi-attacher
  k8s.gcr.io/sig-storage/csi-provisioner: antidebug/docker-image-sync/csi-provisioner
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: antidebug/docker-image-sync/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-resizer: antidebug/docker-image-sync/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter: antidebug/docker-image-sync/csi-snapshotter
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: antidebug/docker-image-sync/kube-state-metrics
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: antidebug/docker-image-sync/prometheus-adapter
  quay.io/prometheus/prometheus: antidebug/docker-image-sync/prometheus
